/*Script for creating tables
* @author: xkocal00
* @author: xslobo07
* @assignment: DnD Club
*
* NOTE: Several attributes appearing in the original model were instead promoted to full entity status during implementation
*/

--Part 2/5
  DROP TABLE adventure_difficulties        CASCADE CONSTRAINTS;
  DROP TABLE adventures     CASCADE CONSTRAINTS;
  DROP TABLE campaign_themes          CASCADE CONSTRAINTS;
  DROP TABLE campaign_types          CASCADE CONSTRAINTS;
  DROP TABLE campaign_threats        CASCADE CONSTRAINTS;
  DROP TABLE campaigns         CASCADE CONSTRAINTS;
  DROP TABLE classes         CASCADE CONSTRAINTS;
  DROP TABLE dms       CASCADE CONSTRAINTS;
  DROP TABLE item_types   CASCADE CONSTRAINTS;
  DROP TABLE items        CASCADE CONSTRAINTS;
  DROP TABLE npc_service_types     CASCADE CONSTRAINTS;
  DROP TABLE npcs          CASCADE CONSTRAINTS;
  DROP TABLE participations          CASCADE CONSTRAINTS;
  DROP TABLE pcs        CASCADE CONSTRAINTS;
  DROP TABLE play_sessions         CASCADE CONSTRAINTS;
  DROP TABLE players         CASCADE CONSTRAINTS;
  DROP TABLE races       CASCADE CONSTRAINTS;
  DROP SEQUENCE itemID;
  
-- Player
CREATE TABLE players (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_id CHAR(10) CHECK (MOD(TO_NUMBER(national_id),12)=0), --rodne cislo, wasn't in model, but was added to showcase the check constraint
    player_name VARCHAR2(80) NOT NULL,
    nickname VARCHAR2(80) NOT NULL,
    pc_count NUMBER DEFAULT 0
);

-- DM. Specialization is not total
CREATE TABLE dms (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    became_dm DATE NOT NULL,
    id_player_parent NUMBER REFERENCES players(id)
);

-- Race
CREATE TABLE races(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_name VARCHAR2(80) not null
);

-- class
CREATE TABLE classes(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR2(80) not null
);

--item type
CREATE TABLE item_types(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR2(80)
);

-- campaign type
CREATE TABLE campaign_types(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_type VARCHAR2(80) not null
);

-- campaign theme
CREATE TABLE campaign_themes(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_theme VARCHAR2(320) not null
);

CREATE TABLE campaign_threats(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_threat VARCHAR2(80) not null
);

CREATE TABLE adventure_difficulties(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adventure_difficulty VARCHAR2(80) not null
);

CREATE TABLE npc_service_types(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_service_type VARCHAR2(80) not null
);

-- Character tables. Duplicates parent fields in child tables. Specialization is total
-- PC
CREATE TABLE pcs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pc_name VARCHAR2(80) not null,
    race NUMBER not null REFERENCES races(id),
    class NUMBER not null REFERENCES classes(id),
    is_alive CHAR(1) not null, --bool
    date_of_death DATE,
    character_level NUMBER,
    gold NUMBER CHECK (gold >= 0),
    player_owns NUMBER REFERENCES players(id)
);

--NPC
CREATE TABLE npcs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_name VARCHAR2(80) not null,
    race VARCHAR2(80) not null,
    is_alive CHAR(1) not null, --bool
    date_of_death DATE,
    threat VARCHAR2(80),
    service_type VARCHAR2(80),
    dm_created NUMBER REFERENCES dms(id)
);

--Campaign
CREATE TABLE campaigns(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_title VARCHAR(80) not null,
    campaign_theme NUMBER REFERENCES campaign_themes(id),
    campaign_type NUMBER REFERENCES campaign_types(id),
    campaign_threat NUMBER REFERENCES campaign_threats(id),
    campaign_description VARCHAR2(4000),
    dm_created NUMBER REFERENCES dms(id)
);

--Adventure, identified by campaign
CREATE TABLE adventures(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_campaign NUMBER REFERENCES campaigns(id),
    adventure_title VARCHAR2(80) not null,
    adventure_difficulty NUMBER REFERENCES adventure_difficulties(id),
    adventure_objective VARCHAR2(1000),
    adventure_description VARCHAR2(4000)
);

-- Session
-- Uniquely identified by date and running DM
CREATE TABLE play_sessions(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date DATE,
    session_location VARCHAR2(160),
    duration_minutes NUMBER,
    instance_of NUMBER REFERENCES adventures(id),
    running_dm NUMBER REFERENCES dms(id)
);

--participated connection
CREATE TABLE participations(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pc NUMBER REFERENCES pcs(id),
    id_session NUMBER REFERENCES play_sessions(id)
);

-- items
CREATE TABLE items(
    --id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id NUMBER DEFAULT NULL PRIMARY KEY,
    item_name VARCHAR2(80),
    item_value NUMBER,
    pc_owns NUMBER REFERENCES pcs(id),
    id_item_type NUMBER REFERENCES item_types(id)
);

--triggers
--primary key trigger for items
CREATE SEQUENCE itemID;
/
CREATE OR REPLACE TRIGGER itemPK
    BEFORE INSERT ON items FOR EACH ROW
    BEGIN
        IF :new.id IS NULL THEN
            :new.id := itemID.NEXTVAL;
        END IF;
    END;
/

--Trigger incrementing pc_count collumn of player when that player creates a new character
/
CREATE OR REPLACE TRIGGER pcCount
    BEFORE INSERT ON pcs FOR EACH ROW
    BEGIN
        UPDATE players
        SET pc_count = pc_count+1
        WHERE id = :new.player_owns;
    END;
/
/*Insert sample data*/

--Players
    INSERT INTO players(player_name, nickname) VALUES ('Jakub', 'Antilos');
    INSERT INTO players(player_name, nickname) VALUES ('Juraj', 'Traktorista');
    INSERT INTO players(player_name, nickname) VALUES ('Jozko', 'Mrkvicka');

--promote to DMs
    INSERT INTO dms(became_dm, id_player_parent) VALUES (DATE '2020-01-01', (SELECT id FROM players WHERE nickname='Antilos'));
    INSERT INTO dms(became_dm, id_player_parent) VALUES (DATE '2019-12-02', (SELECT id FROM players WHERE nickname='Traktorista'));

--Create types
--Races
    INSERT INTO races(race_name) VALUES ('Human');
    INSERT INTO races(race_name) VALUES ('Elf');
    INSERT INTO races(race_name) VALUES ('Dwarf');
    INSERT INTO races(race_name) VALUES ('Halfling');

    --classes
    INSERT INTO classes(class_name) VALUES ('Fighter');
    INSERT INTO classes(class_name) VALUES ('Wizard');
    INSERT INTO classes(class_name) VALUES ('Ranger');
    INSERT INTO classes(class_name) VALUES ('Cleric');
    INSERT INTO classes(class_name) VALUES ('Warlock');

    --item_types
    INSERT INTO item_types(item_type) VALUES ('Weapon');
    INSERT INTO item_types(item_type) VALUES ('Armor');
    INSERT INTO item_types(item_type) VALUES ('Wondruous');

    --campaign_types
    INSERT INTO campaign_types(campaign_type) VALUES ('Dungeon Crawl');
    INSERT INTO campaign_types(campaign_type) VALUES ('Investigative');
    INSERT INTO campaign_types(campaign_type) VALUES ('Horror');

    --campaign themes
    INSERT INTO campaign_themes(campaign_theme) VALUES ('High Fantasy');
    INSERT INTO campaign_themes(campaign_theme) VALUES ('Steampunk');
    INSERT INTO campaign_themes(campaign_theme) VALUES ('Cyberpunk');
    INSERT INTO campaign_themes(campaign_theme) VALUES ('Dieselpunk');
    INSERT INTO campaign_themes(campaign_theme) VALUES ('Ancient Greece');
    INSERT INTO campaign_themes(campaign_theme) VALUES ('Victorian');

    --campaign threats
    INSERT INTO campaign_threats(campaign_threat) VALUES ('Minimal');
    INSERT INTO campaign_threats(campaign_threat) VALUES ('Medium');
    INSERT INTO campaign_threats(campaign_threat) VALUES ('PCs May Die');
    INSERT INTO campaign_threats(campaign_threat) VALUES ('Deadly');

    --adventure_difficulties
    INSERT INTO adventure_difficulties(adventure_difficulty) VALUES ('Low');
    INSERT INTO adventure_difficulties(adventure_difficulty) VALUES ('Medium');
    INSERT INTO adventure_difficulties(adventure_difficulty) VALUES ('High');

    -- npc services
    INSERT INTO npc_service_types(npc_service_type) VALUES ('Shopkeeper');
    INSERT INTO npc_service_types(npc_service_type) VALUES ('Healer');
    INSERT INTO npc_service_types(npc_service_type) VALUES ('Fence');
    INSERT INTO npc_service_types(npc_service_type) VALUES ('Boss');

    --end types

    --PCs
    INSERT INTO pcs(pc_name, race, class, character_level, is_alive, gold, player_owns) VALUES ('Osborn Greencarrot', (SELECT id FROM races WHERE race_name='Halfling'), (SELECT id FROM classes WHERE class_name='Warlock'), 3, 1, 20, (SELECT id FROM players WHERE nickname = 'Antilos'));
    INSERT INTO pcs(pc_name, race, class, character_level, is_alive, gold, player_owns) VALUES ('pc_1', (SELECT id FROM races WHERE race_name='Human'), (SELECT id FROM classes WHERE class_name='Fighter'), 3, 1, 20, (SELECT id FROM players WHERE nickname = 'Antilos'));
    INSERT INTO pcs(pc_name, race, class, character_level, is_alive, gold, player_owns) VALUES ('Humpty Dumpty', (SELECT id FROM races WHERE race_name='Dwarf'), (SELECT id FROM classes WHERE class_name='Fighter'), 18, 1, 6969, (SELECT id FROM players WHERE nickname='Mrkvicka'));

    --NPCs
    INSERT INTO npcs(npc_name, race, is_alive, threat, service_type, dm_created) VALUES 
        ('Arnulf Halfoot', (SELECT id FROM races WHERE race_name='Halfling'), 1, 'minor', (SELECT id FROM npc_service_types WHERE npc_service_type='Shopkeeper'), (SELECT dms.id FROM dms INNER JOIN players ON dms.id_player_parent=players.id WHERE players.nickname='Antilos'));
    INSERT INTO npcs(npc_name, race, is_alive, threat, service_type, dm_created) VALUES 
        ('Throd the Furry', (SELECT id FROM races WHERE race_name='Dwarf'), 1, 'deadly', (SELECT id FROM npc_service_types WHERE npc_service_type='Boss'), (SELECT dms.id FROM dms INNER JOIN players ON dms.id_player_parent=players.id WHERE players.nickname='Antilos'));
    --Campaings
    INSERT INTO campaigns(campaign_title, campaign_theme, campaign_type, campaign_threat, campaign_description, dm_created) VALUES
        ('Humpty Dumpty and his Journey',
        (SELECT id FROM campaign_themes WHERE campaign_theme='Cyberpunk'),
        (SELECT id FROM campaign_types WHERE campaign_type='Horror'),
        (SELECT id FROM campaign_threats WHERE campaign_threat='Deadly'),
        'Join Humpty Dumpty and his band of merry animal friends on their journey to free wonderland from the grasp of an ancient lovercraftian abomination',
        (SELECT dms.id FROM dms INNER JOIN players ON dms.id_player_parent=players.id WHERE players.nickname='Antilos'));
    INSERT INTO campaigns(campaign_title, campaign_theme, campaign_type, campaign_threat, campaign_description, dm_created) VALUES
        ('John Deere and the Magnificent 9420R',
        (SELECT id FROM campaign_themes WHERE campaign_theme='Dieselpunk'),
        (SELECT id FROM campaign_types WHERE campaign_type='Dungeon Crawl'),
        (SELECT id FROM campaign_threats WHERE campaign_threat='Minimal'),
        'Chase the slightly-deranged-but-still-comical mad scientist John Deere through a series of farm themed automobil factories, and help destroy the 9420R he has been using to terrorize the good people of Fordvile',
        (SELECT dms.id FROM dms INNER JOIN players ON dms.id_player_parent=players.id WHERE players.nickname='Traktorista'));

    --Adventures
    INSERT INTO adventures(adventure_title, adventure_difficulty, adventure_objective, adventure_description, id_campaign) VALUES
        ('Baron Cupcake and the Decaying Memories',
        (SELECT id FROM adventure_difficulties WHERE adventure_difficulty='Medium'),
        'Survive',
        'TODO: Description',
        (SELECT id FROM campaigns WHERE campaign_title='Humpty Dumpty and his Journey'));
    INSERT INTO adventures(adventure_title, adventure_difficulty, adventure_objective, adventure_description, id_campaign) VALUES
        ('Shadow Hounds of Omellete Castle',
        (SELECT id FROM adventure_difficulties WHERE adventure_difficulty='High'),
        'Escape',
        'TODO: Description',
        (SELECT id FROM campaigns WHERE campaign_title='Humpty Dumpty and his Journey'));

    --Sessions
    --Duration is updated after session ends
    INSERT INTO play_sessions(session_date, session_location, instance_of, running_dm) VALUES
        (DATE '2020-02-04', 'Kachna', (SELECT id FROM adventures WHERE adventure_title='Baron Cupcake and the Decaying Memories'), (SELECT dms.id FROM dms INNER JOIN players ON dms.id_player_parent=players.id WHERE players.nickname='Antilos'));
    --Insert Participants
    INSERT INTO participations(id_session, id_pc) VALUES
        ((SELECT play_sessions.id FROM play_sessions WHERE play_sessions.session_date=(DATE '2020-02-03')), (SELECT id FROM pcs WHERE pc_name='Humpty Dumpty'));
    INSERT INTO participations(id_session, id_pc) VALUES
        ((SELECT play_sessions.id FROM play_sessions WHERE play_sessions.session_date=(DATE '2020-02-03')), (SELECT id FROM pcs WHERE pc_name='Osborn Greencarrot'));

    INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_0', 0, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_1', 319, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_2', 580, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_3', 819, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_4', 1056, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_5', 1485, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_6', 2634, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_7', 2681, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_8', 2104, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_9', 36, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_10', 3980, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_11', 1298, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_12', 1308, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_13', 4524, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_14', 3640, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_15', 3180, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_16', 1872, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_17', 4420, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_18', 6030, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_19', 1881, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_20', 3960, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_21', 8904, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_22', 4400, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_23', 7705, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_24', 1464, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_25', 9375, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_26', 10582, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_27', 8586, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_28', 6776, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_29', 5133, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_30', 3270, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_31', 12028, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_32', 11008, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_33', 5049, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_34', 884, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_35', 7665, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_36', 2808, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_37', 13838, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_38', 11096, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_39', 12207, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_40', 6200, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_41', 10824, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_42', 7560, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_43', 2365, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_44', 20152, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_45', 5490, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_46', 4462, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_47', 21338, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_48', 1632, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Weapon_49', 1421, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Weapon'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_0', 0, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_1', 350, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_2', 874, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_3', 1242, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_4', 1408, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_5', 280, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_6', 906, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_7', 3262, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_8', 2520, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_9', 3771, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_10', 1950, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_11', 2486, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_12', 1692, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_13', 3094, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_14', 2450, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_15', 7245, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_16', 3968, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_17', 2737, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_18', 6534, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_19', 8911, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_20', 1560, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_21', 945, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_22', 242, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_23', 2300, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_24', 6576, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_25', 2450, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_26', 4706, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_27', 11151, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_28', 9044, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_29', 11455, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_30', 10740, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_31', 589, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_32', 9728, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_33', 7029, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_34', 10642, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_35', 14280, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_36', 9540, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_37', 5069, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_38', 4294, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_39', 14586, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_40', 5200, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_41', 328, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_42', 3150, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_43', 1548, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_44', 19052, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_45', 135, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_46', 5980, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_47', 17672, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_48', 8160, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));
INSERT INTO items(item_name, item_value, pc_owns, id_item_type) VALUES ('Armor_49', 19845, (SELECT id FROM pcs WHERE pc_name = 'pc_1'), (SELECT id FROM item_types WHERE item_type = 'Armor'));


--Part 3/5
    
    --write session date and location of adventure Baron Cupcake and the Decaying Memories
    SELECT s.session_date, s.session_location
    FROM adventures a , play_sessions s
    WHERE s.instance_of = a.id and a.adventure_title = 'Baron Cupcake and the Decaying Memories';

    --write class name of pc osborne greencarrot
    SELECT c.class_name
    FROM pcs p , classes c
    WHERE p.class = c.id and p.pc_name = 'Osborn Greencarrot';

    --write campaign title and adventure title of 4.2.2020 session
    SELECT DISTINCT c.campaign_title, a.adventure_title 
    FROM  adventures a NATURAL JOIN campaigns c, play_sessions s
    WHERE s.session_date = DATE '2020-02-04';
    
    --group by a agregacna funkcia
    --sorted campaigns by types

    SELECT COUNT(c.id), campaign_type
    FROM campaigns c
    GROUP BY campaign_type
    ORDER BY COUNT(c.id) DESC;
    
    --write last dms
    SELECT d.id , max(d.became_dm)
    FROM dms d
    GROUP BY d.id;
    
    --exists
    --write player name whose not dm
    SELECT p.player_name
    FROM players p
    WHERE NOT EXISTS
    (
      SELECT d.id
      FROM dms d
      WHERE d.id_player_parent = p.id
    );
    
    --in
    --write info about dm joined in 2019
    SELECT *
    FROM players p
    WHERE p.id
    IN 
    (
      SELECT d.id_player_parent
      FROM dms d
      WHERE d.became_dm BETWEEN '1-01-2019' and '31.12.2019'
    );
    
-- Part 4/5
SET serveroutput ON;

CREATE OR REPLACE PROCEDURE adventures_percentage (campaign_id_arg NUMBER) AS
  BEGIN
    DECLARE CURSOR cursor_adventures  is
    SELECT A.id_campaign, A.id
    FROM  adventures A;
			campaign_id adventures.id_campaign%TYPE;
            adventure_id adventures.id%TYPE;
			all_adventures NUMBER;
            camp_adventures NUMBER;
            adventures_percentage NUMBER;
		BEGIN
        all_adventures := 0;
		camp_adventures := 0;
		OPEN cursor_adventures;
			LOOP
				FETCH cursor_adventures INTO campaign_id, adventure_id;
				EXIT WHEN cursor_adventures%NOTFOUND;
            if campaign_id = campaign_id_arg THEN
            camp_adventures := camp_adventures + 1;
            END IF;
            all_adventures := all_adventures + 1;
			END LOOP;
			CLOSE cursor_adventures;
			adventures_percentage := (camp_adventures / all_adventures) * 100;
			DBMS_OUTPUT.put_line('Campaign ' || campaign_id_arg || ' have : ' || adventures_percentage || ' % of all adventures');
			EXCEPTION WHEN ZERO_DIVIDE THEN
				BEGIN
				DBMS_OUTPUT.put_line('No adventures found' );
			END;
		END;
END;
/
--EXEC adventures_percentage(1);
--EXEC adventures_percentage(2);
CREATE OR REPLACE PROCEDURE dms_percent AS
    all_players NUMBER;
    all_dms NUMBER;
    percent_of_dms NUMBER;
    BEGIN
    SELECT COUNT(*) INTO all_players FROM players;
    SELECT COUNT(*) INTO all_dms FROM dms;
    
    percent_of_dms:= all_dms / all_players * 100;
    DBMS_OUTPUT.put_line('there is ' || percent_of_dms || ' % dms of all players.');
  EXCEPTION
    WHEN ZERO_DIVIDE THEN
    DBMS_OUTPUT.put_line('No players created');
  END;
/

EXEC dms_percent;

GRANT ALL ON players TO xslobo07;
GRANT ALL ON adventure_difficulties TO xkocal00;
GRANT ALL ON adventures TO xkocal00;
GRANT ALL ON campaign_themes TO xkocal00;
GRANT ALL ON campaign_types TO xkocal00;
GRANT ALL ON campaign_threats TO xkocal00;
GRANT ALL ON campaigns TO xkocal00;
GRANT ALL ON classes TO xkocal00;
GRANT ALL ON dms TO xkocal00;
GRANT ALL ON item_types TO xkocal00;
GRANT ALL ON items TO xkocal00;
GRANT ALL ON npc_service_types TO xkocal00;
GRANT ALL ON npcs TO xkocal00;
GRANT ALL ON participations TO xkocal00;
GRANT ALL ON pcs TO xkocal00;
GRANT ALL ON play_sessions TO xkocal00;
GRANT ALL ON players TO xkocal00;
GRANT ALL ON races TO xkocal00;

GRANT EXECUTE ON dms_percent TO xkocal00;
GRANT EXECUTE ON adventures_percentage TO xkocal00;


DROP  MATERIALIZED VIEW adventure_campaign;
CREATE MATERIALIZED VIEW LOG ON adventures WITH PRIMARY KEY, ROWID;
CREATE MATERIALIZED VIEW LOG ON campaigns WITH PRIMARY KEY, ROWID;

CREATE MATERIALIZED VIEW adventure_campaign
  NOLOGGING
  CACHE
  BUILD IMMEDIATE
  REFRESH FAST ON COMMIT
  ENABLE QUERY REWRITE
AS
SELECT adventures.rowid AS adventure_id, campaigns.rowid AS campaign_id,
campaign_title, campaign_type, adventure_title
FROM campaigns JOIN adventures ON adventures.id_campaign = campaigns.id;

GRANT ALL ON adventure_campaign TO xkocal00;

SELECT campaign_title, campaign_type, adventure_title
FROM adventure_campaign;


 INSERT INTO adventures(adventure_title, adventure_difficulty, adventure_objective, adventure_description, id_campaign) VALUES
        ('Some random adventure',
        (SELECT id FROM adventure_difficulties WHERE adventure_difficulty='Medium'),
        'Survive',
        'TODO: TODO',
        (SELECT id FROM campaigns WHERE campaign_title='Humpty Dumpty and his Journey'));


COMMIT;
SELECT campaign_title, campaign_type, adventure_title
FROM adventure_campaign;
DELETE FROM adventures WHERE adventure_title = 'Some random adventure';
SELECT campaign_title, campaign_type, adventure_title
FROM adventure_campaign;
COMMIT;
SELECT campaign_title, campaign_type, adventure_title
FROM adventure_campaign;

--explain plan and index
EXPLAIN PLAN FOR SELECT item_types.item_type, COUNT(items.id) AS NumberOfItemsLessThan100Value 
FROM items RIGHT JOIN item_types ON items.id_item_type = item_types.id where items.item_value < 100 
GROUP BY item_type;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
--explain plan and index
CREATE INDEX item_value_idx ON items(item_value);

EXPLAIN PLAN FOR SELECT item_types.item_type, COUNT(items.id) AS NumberOfItemsLessThan100Value 
FROM items RIGHT JOIN item_types ON items.id_item_type = item_types.id where items.item_value < 100 
GROUP BY item_type;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());